### ISSUE TITLE
[BUG] Filtered Storage Chest brokes the import

### ISSUE THREAD

**Issue by DHKold** [teoxoy/factorio-blueprint-editor#115]
**Describe the bug**
When trying to import a blueprint with a Filtered Storage Chest, it fails.

**To Reproduce**

1. Create a blueprint with a Filtered Storage Chest
2. Click on the Storage Chest and set the filter to Uranium Fuel Cell
3. Export the blueprint using CTRL+C
4. Clear the screen (F5)
5. Import the blueprint using CTRL+V

**Expected behavior**
The blueprint should be imported.

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser: Firefox

**Additional context**

<details><summary><strong>Blueprint String</strong></summary>
0eJx9kE1qwzAQhe/y1jLYhDREy16jhCArE2dAllxpVGKM7h45bkNW3QzM3/fezILeZZoie4FewDb4BP21IPHgjVtrMk8EDRYaoeDNuGYuDJyEbWNvlKRJEqIZCEWB/YXu0F05KZAXFqaN+P+mwhRSHQ5+1ayAVmGusRIvHMlunfaXOZ99HnuKVUch0neuqPOVnVDcxP5cvAznaDznsblmco0l51BOq8XnWfrtCwo/FfJUO+zabr/76PbdUcGZnuo/8PmaLOUBSblsIg==
</details>

**Comment by Teoxoy** [comment]
Thanks for the report!
I am currently working on something else for the editor and will fix this after.
