### ISSUE TITLE
[BUG] Some default keybindings doesn't work

### ISSUE THREAD

**Issue by baryluk** [teoxoy/factorio-blueprint-editor#179]
So, I use Firefox 68.2.0esr, and I am not sure what 'modifier+s' is. I tried shift, alt, ctrl, win key (meta). Nothing works.

I can't also select an area to select entities and do something with them (like delete, copy).

I tried various key modifiers and dragging mouse with left, middle and right mouse buttons. It doesn't do anything.

**Comment by Teoxoy** [comment]
modifier is either ctrl (windows/linux) or cmd (mac)

I tested with firefox 70 and all the mentioned keybinds work.
Can you retry or give some more info?
