### ISSUE TITLE
[BUG] Can't close the INFO dialog using Esc, or I key when hovering over dialog

### ISSUE THREAD

**Issue by baryluk** [teoxoy/factorio-blueprint-editor#180]
Title says it all.

When you open INFO dialog, using I, you might want to close it. But if the mouse is over the dialog, the I and Esc do not anything. They should close it.

**Comment by Teoxoy** [comment]
This only happens when the canvas loses focus since the keybinds are attached on the canvas.

I will add an event handler on the info div too.
