### ISSUE TITLE
Resolution doubled on retina displays

### ISSUE THREAD

**Issue by hoylemd** [Teoxoy/factorio-blueprint-editor#2]
I tried to use the app on my macbook and the app is drawn as if my screen was 4 times the size it actually is:

<img width="1396" alt="screenshot 2018-05-30 11 09 36" src="https://user-images.githubusercontent.com/569403/40729320-1ccbec6a-63fa-11e8-9d32-013078cf7232.png">

I'm pretty sure it's the retina display because I was able to use the app without this problem yesterday on an external non-retina monitor.  The problem is also happening in Chrome and Firefox, so it's probably not browser-related.

If you accept pull requests, I can try to get a patch up.

**Comment by Teoxoy** [comment]
You can try changing the resolution to 2 [here](https://github.com/Teoxoy/factorio-blueprint-editor/blob/0eca48c98f0f1cbb8400a4b5ba98d83409e9984e/src/app.ts#L76); the [PIXI.js docs](http://pixijs.download/dev/docs/PIXI.Application.html) recommend 2 for retina displays.
I thought `window.devicePixelRatio` would return 2 for retina devices.

**Comment by hoylemd** [comment]
You're right, `window.devicePixelRatio` returns `2` for retina devices.  I forked the repo and played around a bit with it yesterday.  hardcoding `1` in there make the app usable, but because it's upscaling every pixel, things look blurry.

I managed to sort of get it working without the weird resolution, but it required dividing by `window.devicePixelRatio` almost anywhere coordinates were used.

I've used Pixi a fair amount myself, on retina devices, but I never ran into this problem (And the games I made looked fine on non-retina devices).  I'm thinking that if I can find a few hours I'll see if I can figure out what the difference is, and that should lead to a PR that doesn't touch *everything*

**Comment by Teoxoy** [comment]
Thanks for looking into it, I can't test it myself because I don't own any apple devices. If you manage to fix it, I would greatly accept a PR.

**Comment by hoylemd** [comment]
I'll try to carve out a couple hours this week.  :)

**Comment by hoylemd** [comment]
I've been working at this a little, but it's proving difficult to implement without significant changes to the UI rendering code.  I have some ideas for refactoring the code (and some of the layout), but I wanted to check with you before I rewrite large swathes of code.  Would you be open to that?

**Comment by Teoxoy** [comment]
Sure. I have no problem with that :)

**Comment by Teoxoy** [comment]
I see you worked on this in your fork. Did you get it to work?

**Comment by hoylemd** [comment]
Sort of, but not completely.  I had to redo how the UI popups are built to make it work with both resolutions, and I just sort of lost interest/got busy with other things.

**Comment by Teoxoy** [comment]
I found a way to test retina displays using the chrome dev tools and I figgured out what was happening.
It was a matter of reading the width and height from the screen property of the app and not the renderer.
Thanks for your involvement tho.

**Comment by hoylemd** [comment]
Oh great! Glad you were able to figure it out.  That's a much better path to a solution than re-writing the whole UI :p
