### ISSUE TITLE
[BUG] The effect of beacons(with modules) does not apply to assembling machine

### ISSUE THREAD

**Issue by Disparity** [teoxoy/factorio-blueprint-editor#218]
Thanks for the editor, a very handy tool.

**Describe the bug**
When you hover over a factory, you can see the crafting speed of this factory (special thanks for this feature), but the effect of beacons does not apply to it, the speed is shown only taking into account the modules of the factory itself.

**To Reproduce**

1. Place an assembling machine and select a recipe;
2. Put a beacon near the assembling machine and place speed modules in it;
3. Move the cursor to the assembling machine, the "basic craft speed" is displayed in the assembling machine information window.

**Expected behavior**
The "resulting crafting speed" is displayed in the assembling machine information window, taking into account the effect of beacons. The correct number of items produced is also displayed.

**Desktop (please complete the following information):**

-   OS: win10
-   Browser: chrome

<details><summary><strong>Blueprint String</strong></summary>
0eJytlN1qhDAQRt9lrhPQ9WfbXPY1ylJiHLYDMUoSS0Xy7o1apL1YIqx36nz5Tg6SzNDoEQdLxoOYgVRvHIj3GRzdjdTLNz8NCALIYwcMjOyWtwZljEJgQKbFbxB5uDFA48kTbg3/kwyG3sVhfIydcQEvGUwgiljRkkW1jbLfkunDjF2DNhazFe2WZW5AbHnXt6NGXoC4hMB2kHQOu0aTufNOqk8yS+QRNkthLwzilFZ11DFne0OKK7JqJA9/uA8F82OCxVHBBCipVJ4E4kml6mlSeZBUP026HiRdTyIlf9PLSaCk0eu5J6s+ppdniZN127a1CO5XE4MvtG5tvBZZXhV1XuVx/1o2GC8peNuTIfwAMwuWEQ==
</details>

In the blueprint, both assembly machines have the same crafting speed, although the assembly machine on the left should receive +400% speed from the beacon effect.

**Comment by Teoxoy** [comment]
I thought I had an issue tracking this but it's actually only a `TODO` in the code.

https://github.com/Teoxoy/factorio-blueprint-editor/blob/9795e8039275d24ed0aa3ee1ed2bf6ecde9f15fa/packages/editor/src/UI/panels/infoEntityPanel.ts#L100
