### ISSUE TITLE
[BUG] "Example blueprint book" link from the readme fails to load

### ISSUE THREAD

**Issue by oconnor663** [teoxoy/factorio-blueprint-editor#223]
**Describe the bug**
Trying to view any blueprint book seems to fail. Since the readme example fails too, hopefully it's not my fault :)

**To Reproduce**
Click on the [example blueprint book link from the readme](https://teoxoy.github.io/factorio-blueprint-editor/?source=https://pastebin.com/Xp9u7NaA&index=1).

**Screenshots**
![image](https://user-images.githubusercontent.com/860932/92612661-129d6380-f288-11ea-902d-edd07fcdfc97.png)

![image](https://user-images.githubusercontent.com/860932/92612775-31035f00-f288-11ea-9e88-34ee9c1ad7c6.png)

**Desktop (please complete the following information):**

I'm on Windows, and I repro'd with both Chrome and Firefox.

**Comment by teoxoy** [comment]
Oh, the example blueprint book is actually a book I use in game and I recently updated some builds for Factorio 1.0
I haven't looked at what changed yet. It's a matter of updating the editor to support Factorio 1.0

**Comment by oconnor663** [comment]
I just tried the link from the readme and still saw this bug, but maybe the live version hasn't been updated with this fix?

**Comment by teoxoy** [comment]
Yeah, not yet. Will post an announcement on discord once I do.
