### ISSUE TITLE
Pumpjack pipes generator

### ISSUE THREAD

**Issue by Teoxoy** [Teoxoy/factorio-blueprint-editor#26]
Configurable pipe generator for oil outposts

**Comment by Chronial** [comment]
FYI, I opened a pull request for my algorithm in factorio-generators: [#47](https://github.com/demipixel/factorio-generators/pull/47/files). A lot of that should be reusable. The pipe code is in `addPipes.js`. You might also be interested in the code in `powerUtils.js`. It contains a function to power all consumers with the minimum amount of poles and a function that ensures that the power grid is a connected graph.

**Comment by Teoxoy** [comment]
It took me a while to get back at this.
I've been working on this for the last few days. The implementation is quite performant (takes around 1-2s for more than 100 pumpjacks).

I attempted to solve this problem in 3 ways up to now... I scrapped the first 2 solutions because they were either not performant or I wasn't happy with the end result (I felt kind of bad when I erased ~1k LOC...).
This is probably the most complex algorithm I wrote as of now 😄.

You can find an explanation of each generator in it's respective file.

I've also exposed 2 interesting parameters to the user: `MIN_GAP_BETWEEN_UNDERGROUNDS` and `MIN_AFFECTED_ENTITIES`. I think the first one is self explanatory but the second one allows the user to specify when a beacon should be placed (if a beacon affects less pumpjacks than the specified value, it's not going to get placed down). I find this useful because you can get the most out of the beacons you have if you are on a budget.

**Comment by Chronial** [comment]
nice :).

It's interesting to compare the output of our implementations: [a](https://teoxoy.github.io/factorio-blueprint-editor/?source=0eJytXdtu3MYS/Jd9FgHOjRz6Vw6CwJdFsDm6QZaCYxj+97OSpkcxVauuIvgWO3KRItk1Xd010z8PX66fjvcPp9vHw6efh9PXu9vvh0//+Xn4fvrr9vP18989/rg/Hj4dTo/Hm8PV4fbzzfOf7p9u7v/+/PW/h19Xh9Ptt+P/Dp/Crz+uDsfbx9Pj6fiK8fKHH3/ePt18OT6cf+D9v7463N99P/+Du9vnK51BhpSuDj/OPzudgb+dHo5fX/9nvHq5ge/PP3b/cPft6fz3/5zBh5vzf18fh3T+kV+/rt5dM75d83T+Nd5fL4eX6w3h9+uNACt5WHF6wao+VPag6gvS4iMVBymN7ffLPtbkYOXX329IPtT8G9TweDf89XD3dPsNvXG7w9UrnwBspWFTfEEtyQddaNDwCjoQbziM6q0SdxreQujm+O30dDMcr88//3D6OtzfXaPvyB5uLCg6QlTx4vKClzOES0yEtxezT3yHzFwyvz6EefXatl7TizkjFeYz8WLu/OZweEC0meOVQERwqCyzMGALSS3Rx4p8ZBkjv3t4EeEGGre93zW5QNQos8vqXjNCTTy7ZMQu8FazzAb21hJce4uM9/qtF8gucaLYZe6E9zudbk0gZuqqrw857MQw0Yu9IVvwra+I0LzgG2KiaSGNHMVk4sZSYCmGoIXkpXpGMUymx4eXvXoqfUmZpxg+f0lFphgiGUwTj5raI1jHHIKdVVJY+vNFcHVjBlMChFuIaA8tB9qHYPJIXDJWmHhuzZqyF3hv/EJkHdkVWcYvxGeXXZU10yIkezKr8wvBCdnL+hq/jAQUH1pDjHwGk3nVVfgMJvOiK0AlgxKYzIuueIFd0L2WUaWD0p5vGlGgFFlwtUdwXv4QXGSSiVYCec6qdon2QsmyMvYH8fvb23pVt8bROYaocriSyyimEGCu5mqSiym/eIqrUwzBC8VL+/LMUkzh42uIQgFmEsRXKDAThLC89hrh4osweeXVNTaRwExJpYTcMsQIM5hJV13jBxnMVIhgbwyzUw1mYoRZ47R1eG69pFvoSAtNLpOrthq5ZIJcJldsZZpcZk9rGbkwWF7KlyvLLTMfWEMQCjCzoLoWSC0QlddcBVELxOQVV1z47GWetlJLgOXdWdZaTcwmWM+ZK5NHmB6OcZ88YmYkWQ/3EvbhtOqWOVKlCaa6cqtl+UwBprpqK9GkUD2x1QiGEIGVD7OhCej1bwsbPnykDSngvBneriDBGodlopxfeQU2sXlM5fVX08ZEwlWXzVkMTDsWWXg1noiw1rtQveIMv86tRLMw4ixkWKPfWvxZ3GpHmmmaWVzFFQNejSGaL7lonlk8xdVClwjcRegshxHyDFp6FyHIjGfWtXdU51gEHdZ4pqwXTthd5nVYCGxaE0ZehgXENBhUbjKbJwMrnDDKCszaMwvGo3rIVoVa9kkwwsgItcFK62UnP0wY3eJHYxzK4+DKsMY4VI94dHWYLfCESAmjJ8QSjAuIJZg5Blypx7B8uA3FfncKWFBo5uggSh8h8AoNK1OMyqeOkc1vQpCbz7lJCFy6DUEVZ43OYdEnBKat3JKN9a+7NfQDpd96QXwns4xr/RgS35gN0dVlES/6GM0VZoHOcUL0hFkjHKKIFAR/hxFOJrKGKIg0I5xQGWBBprXFeE04MHeIvEzDqhej8jlk4POcKLeie6jhvCSqGi1aWRd685g+s5VR1ivsVk0VEiXkLMvJ6yR182X9Ignt1Q3JFWlhpuvDIXkqja8Ph+S6fwNbvwmC38MsPgyqINeKoE5DUgRb6xlRuLxgw11CmI1kpW2GhQa82yz3p1P5qBkVsirWWr8bF6BDZlrPEVattjuCKTlX4Kq5Obdy3SH9wTNZTnZFmjEO80lnT6VlXrJk1xUMF0yMJdRGKqz0IdQihFpnnMAAC2qtMQ5Vyim8WAs4HYXpSBFSSHsM61Uf4sr96uZAvuClV3VacxUE6NcJhTMJjxdy2807AgQ5N6wbCZtJx/WLGOkwkV1cnWacw8T25Om0C1syIJZrExa2WwiVkcU+NAJWCLZyIdowsKDYWpwxluEwCYLNWGddg8Q3LNuGmcLTJHeyW28IB86kSrVmmKkYjelQ40jcHPozo+YGXFjZflG3XNJ+y/UniPcquRrNGq8MScyeSOvWdwrNdQ6/xgSTowtmEaMcJm2YBb1mlFMYXGXrJu8iDrMg2DrjEE7iMAv7N2foe0OoVXcSZyucQjxVqTXLP9ZVlelVd1fjuk+5Nf4ro+ZKgqnvZtKpblc79V1jfjBWV6dZF5baIunpNCOdtRkKo7le4sBnJIprpG3jY9yvoQqizSzl6w8QAi+Cbmt2KapntQiyrfMOI9IXpclmVRfm1S26w7i9QBhAiyrYWuqEBdZCta3blvZ3X+pWElgoizG2ymxmnsU3GVtTlqGexW9vK1u9F0+vGfcwWyLi6FqNG/cQkREFG0m3ZhBrchyFiOvnehCtmzgqtZJKt6/iqJgiA64OwO3fo9Jvu5QGQGDZgmwvEO/ZHlXhlktzgkE0poOd7LvfSWvFkXMgt7xhHbtbrxp8B7LQL4nB1W598WO2lAdPvAXeHRiDa0MOUBdhMCHmhMQnBiHk+s42hnqDIOTsQVBvXHdKvhPH+Ekorbe2Jr+TAxBYNiW3OnvAIRRVDZfMlA3RqFZ2a2btlfnEyCi9IaeWsu3SQovRtyXTJdcYXQHXmYeJ7+gpOGMeJvaiJ+DaYsKwmOAqkbKeKIRbxrY7uNRHQcm1173eWYGPpuGF3AXWgY8h6e23dx8UBpb9yclsiBBOVW+2FR+HYqK62flCrr+ZARIn81rHYd0+3XxV35wcYODAgEyufus5N5PyJE+/2dZ/Bss1JyeadxRvSeOHdWYMYYV4M9phloMsiDijHeaRZl7DXXjr+DEo6eQiJDtZNij3chqs88SsSrd2mgA+yy9mpqXdNpy9809sJYBMWZRbUrkuRWy+qO9QblsFmPykuLqtsw6TxRdPtwV4niLGch3KVipgAlkxmLTNsuvjiyCsEHDGO0S/LBZ9J2micIWG9wXiwc9BSScvJNAYWG1+984pbH/Hoqq2JlYSdCDGielsm16NO233jhMl7lritw7c7Vf1bcr2izJL4OQble0LZOhi8oRb+zAYGptcp7JRD8OxgsnEclQm5Zn0kGPMNnHSN5cmov0YJ17B9cfL1O9npRV3QWrBB/EvAwlZkPmQeWZVubXtDfECHNPeDriztZkCZkbftb33e5Hd7JuVoU7AH4ur2RZaysyeYgtwAyDGcp3KxfwaBJhSK4l0rlOFQDPvCnOQb1VqJS23JSzQsfLaLWGDPYZV2m9RSHWq7FWePiScqmq29hQi7KXHKnW192osVUrY2bbgnTaCxep7lUe+tFNdyYaPmMHHI3uKLcCIxliuV9mcIAyYXiphHt6ihBs2dMLVfeGVW5cUTO648MotXeh1Y1y51z1ZmQvCyR5l83tcqMAssku5WDUGwlE25QQLOlt752lk1JyF/rq7sPmivk95pAs6aXRFWqUTiTS6NuXMZktpdE3K/JazpDhK8B4vtLSnUVBqfIKTRmEH99sma+J2hQEz9nCJnlga1RpJU1X4zPOg9rU705QLgLI5+SMmTIHqWfejIdelja1hT46faTWcvcgm+P7kEV4RhqE/W6bS+UNyh8s0smEMxcmdLdMCgsJSzMkLW79JQVBp2OUNYYWBM51siFwxCQNn7IgU6nb187Z68xjiyXbkntfADnmS58zYxknMNpFqVZvVa6+w56bRvF50p60QKfqG5NFaesTn5yoy/oTT5M6YMaqhpq+4ZuQCG4AQS/Eiw5PPYAKShEoIn9YIc2c60xB1m6TMncFVMXy7+hlbLR4gmizHumsRE4M8asYmTVyAo8zHM84KN8c8NZGmH7W/3uC39arZbWIb0xAFh+SPm6HPHk/usBkjGiZBcofNWP2OwVJ2avOpUuZ1Gb/9OwkTaDrRUHfL67LuXicaRynLZ2vNttxDONlobNSQYSU3yXNnbKBTwFxTmHa0taJ2GhOTqOk0AY4T3ExvxXcaj/Czhp+fP3Om0omDO3ImvqXNBJprNC7ouWIsZYd2oUs1hRdl5jlikgRhEk3fLcuUVIRJNCljqoH3O6m1kJbUYPE0yWLMHB/pAqCqxnqdCpd+Jqb/3BXiTj6/RE2psSEf61ro5ov6s3bt+ENqPiI5bJdJHtwRNO3OiHZJcifQJDjnBGIpTpD24TKV65kXZQHLJzxaUp+1uzaQ4dsVZFmB2Se+XbUOUvs9QzhZjXWqwUmNPI4mvokfiMc1ni84/LdGPTW1plmh16G6+Zr+xN2FbnYnfxZNpXMHdxRNn1fHzO91Z9H0o52ZeqhiAzGzAGEvScJomigkNsJomr4VnzjAMAmjaWxsEJPXVLUa8vYhQDhZkbXW8oVijTyQxgY+4jG+VNvZ6Gonj0viptbYKc07nXWcFrc/3cQmRTb+RJrKWvCSO5Cmkw2T17gDaXrtjSGbRbEQL/g24aouDKiJQm4jDKjpbMNkeMKAGos4IrfJo96irv0hQ0D9pOPe4oN4qjCbPujI55FqPV9Y8zcPDnerHf2oSSJa8+i2nm1vO8Ej2Z8zA7cEYSx6yC51Z64xuPI8kkfdGczN8hZmzgjH8GVh5kznEeJY4CyMnHk7tIG4XX3Wkyk7KGpyUEWXdY7zOdP44zVUz//2y/XT8f7hdPt4/gf/HB++vzJhneNYYknPHPZ/XTITtw==), [b](https://teoxoy.github.io/factorio-blueprint-editor/?source=0eJy1XdluJEcO/JVBP6uByqOu+Qnv+8Iw5mh4e1dqCVLL8GCgf3ePKlneqcyqCqYZj5asbk4eDDKSQX4/fL5/PT09ny/Xw8fvh/OXx8vL4eO/vx9ezr9fPt3/+Nn129Pp8PFwvp4eDneHy6eHH//19Prw9N9PX/53eLs7nC9fT38ePrq3u5o/82+/3h1Ol+v5ej5NX738f+8OT48vt18/Xn587u1PjiHcHb7dvrG7fczX8/Ppy/RLfzd/6+Xp9Xr7w9s/5zL99vbR39/ef3B9frz/7fPpP5/+OD8+Tz99//pvv11eHz6fntO/RKw43z4wt6Bt3y04+p8taIws8PsW+LQGkWNB2LdgmAzgfH/c/X6XtiBwDGh3DQj+3YCB8/3d/vd30wK4kWNBv7DgeH08/v78+Hr5WrqS7t2YtvnZls7IlkFhS2yLNyMamTKqliUkP0FaF9dorIkxnZhIcpz/7zkfTl/Prw/H0/3tc57PX45Pj/clL5JuUST5Mef1JvnJs3nSzXY/+dZ1lJsWpiUdnIgZkU5MT7Ji38vOUEsCGrfvaI9+cm6RZcLS066CLSnccEv3WkDbSEVbt/Sqq3BLAju/dKQFA1ou3vpl3LmNLMk9kM6kX4agCOK2JFuWwejmwniBXFJ24Jeh6aY1rUuHZrE2VtGIb9X4Fvt3kxrSZnUVgDtFsssgycykHgTcPp2clnRyBtCOyde6nrQc+75WQJe0IWHf2c6YyzIBSPKnbehIBgA5voAuy7GG/Sw/5XUkyAv7aX6IXNQNyxAUQl1SbhmWwSiCuj3JFlX+79sy6lplCkHDAMyou/TkZodm1INcZEbwsdEb5KacIpLWKNaQAdMiRdJdjx4CYDdOVnBOcsTS/0RCHEkkRNz3vEdxMCQLgNw/BQGBdR6A3D8dyZZ1S4Dc3wVuGBD30//k3ln7sB+RenIo1KqIVAlOSYlCq2EC4pQ8uYHjrloNEXCUbHcRBVjFJK2KCZijAJY1sSLVlRyT9Wyl5wPEv7ACgbaCEZDnJNKrQAsyAvPzTSCdIJARaJvEvjYkO3BKgBQNdDglEEhXpwMogXQgWNFAt08KDOUHRTMLgId/78t+1cyG/djUj9xwoNOxAk3RgVpBcKdhBdpQDAesQpNOxQpIOECKG7s6UoBVsVFBCgTHDQf6Cl4gxfos7O0reIHkcZbVJWYmYbyAOH8OBvcYL5AiEpYRAC0QRiaT1SO0QEMNBHqEFvDUQKDfpwVcx3ye6Pc5gb/jANYiqEqt2liKT80K0HT8gC/yVlYgPGj4AVkXEgYPGn6g4VbDDUENLa4vcb1mi6NnCOJArYcbWizjFL7Ne9IR7sAMPAX6yzoXMzsA/jXx4CTAGxBPO12c5WaYmQCk/z21/mvcT/8T3pGwZgSS/xnvSHdzVFGtwvty7sWoq7nqi3hn5ddHTclVwju/sMWs/FvDDPRlvDPbJD2zmnIY1jXu9bldOsck1zYOegSe3H0gRdbjiCFfbJjxvWsayAwpQSI9obgGEVsJjcTSCDRILdZIhWDXwIorWg12A4iuiqBjZwGQ/Lt0GlpSeaRrNHSraGoWx8JO36PjW5Mmj2aNhnBNQLx8s7LbJw09IM8mjuTHnJ5oTdwvS2VUJcZqmTG2qxBjRVeM5uxMAsVYUoJDYnQcqseSWqCWpX2GJFmeDMiIKCsB8rLUxM4GWJXFUoE7RJfVc28swAzMgMxahkybtQ3ITQmQze6HTqXlmiIg21mjoQwSIC8lFWYYqNJpydVhnVxfUZyVjg5NilxTmzXdb8eK+SvkWmHgZkKgXCtlpj3rZqGlWb6YlJmF3JBaK5DxGBFsCR6zLjSi2Bq4UnFEs+VXSmDtjABEW4FZre0y1dZ2cdTAVFM4nX4rnVFWFqjSbwkc006rhjoYufItF/Q87JFc8u9qVFw9NWevkHElfQptkX6ScW2UJckBYjW6AbVbc4K8fEA3CwwiQNS2K4127HYFqNMSQKbZADAFXfH1wM4EhCeIZEAGJFyBKqd3mYAL6UlFux+qqq2xFMSbLYxK1ZUu7bLI1Cw4UKm63EqNvdk2tXouVsgM1jFu9eVbEiOwctEWo2VT/QOtSxZYtJU0+KxQu0XqYovaabv9QOSyI5cyaYGCrZ6Le4Bea46DWDYAiq30wsXyF5lga7tGaSyF7maXI5NubRozlGo77GzRELGpkp0Vt2dirk3UE70lqaeJ6/QU7Nz2jRWkdHoKtuW6lw5tmJXquZdiM7vtwkhYCfEjzQ6AhE3Ix0KdHqFgE6NEswGgYPuiPsnOhH0KdkY+mg1w2yxaw1AVA+uLpJVZJpEptrZlOiXks7NFQ8Am6oxUnOsyDReCfIGFMn0FAevkPYUVzvd6Bnamc0gmDVhdbIoKWNHkgLGuwq+RRG8uE3eVcM9TM74BaUjQcHFvANjWvph725mwT7a6lca3djYAMwkcs5jfZWotpC0D6xk0E25tG0NliDIF1ybulTuqm0XLmZgLAj5W7D7q62Cl9x4t5RsryFdPZcpHsCvhSjJst1sY4ZoqXmglh5nKq3SjufXbI8C2CvDRlmGfbi2XP9lZsE+2DmTYG/eT/3QUWA27G1UBbIK9Jf9t1nE+k2xtundmkZ7PhFsQ7LFGJmQSLgT3WEJ/31QUwCaOfFmubGeTnn6V6nKeTWgnAk99/fQNRrqGnpry+UzitY58NHcHsK2CfKy7nA3WWkM+1iK4fa41USG0cTRI8i/v77R9qOlDsCyGM7scTsO7+hLTaYbCmU4LYDqzUkozIM4EW0htC6t9sncVbQgCVW7vXQ39KjI7FuQ4rBVBEDtILwjeY5zrMU28ZGkffabtWsc+1jnJBF0lL5eaI5NyLp/puAo2FMU3dhbA419Z4OcRAkDAj3U/vaoTgS9XgtvdDg35KuWLrJXRcK+hKaOfWViQabSAlWE1C/ahpuVrpJbM+VDT8zWUUcfOKFBRIEEl65YHsAVBDMxCLQ/M4prb8rNWAu/9SgO/TMJVsoFMSWTKrQL8dVT4y8ZtrXKevEVQ6Qik8w2ppNJHDQUrT1osWzQE7Nwpn8UzRg0H68iZX6yREJB1hj7qmViprKSZBCoKoieHThFlX5M4h9Tu0iNzuKTnN2tP8EawrHdPD0ziOrIJ+Uy0tYp+rMgwU2qtox+L91SO3XJF9DO7Haq5W678JGxnjIqEFfgjqfp8W9F/gJf81cza4sqlfKsnY2VIGs/FgM1d+uIlt9stsBVsevNjmQHN3uJ6XGT2lmAfy+UCw7ca8rkEpm8l6GMxr8DsLYE+Fh+im70lak/agqhetmQKNssYFQU7lGN3MyDWjd+SQo6lINUMiSvmbzm50CwepWL+lkQsrDPUY9ICWZrly74Z6oBDt2Z9ASu2BdRc8jjMQj9k6pagH8vrAnO32IkfMHfLF2U3dhbsswCJEaGtgc6npqb0pEp+r5rA5YpNbsxsUU3gmuvUWYmWagTX3y1yWbHroBcUCI/DCpwqhnGVW/faWYRpC1y50NMMcMARXJE6z84DYi557qMR48jwLSn0pNkA9NimShw8Mn1rHj3FMgIYwDXXz7PuZzaDa7vcJTkL2oqo3rWoQ4y8ahrXvE+sREs1jmuuYly+WZj501EvKhDdNAv7KgZzSZ9cXi46KgUGrKf0ESRfUyK8bFdvd26Qpi4NFQFDpuzaQEDSA34ARnDNYiWWCUjVq0AgyckGYAKXjIZjWaBr6zKdi7BYDys3H7JhXAAARpYtqr4uAoAkmiDohnL5FQC0cqih0WsL0nPOkbZCFa2140C+4A5s7RKor37Bgb1dEvaQqsgCJO9K8Mfy+5m6a/15mnYoAKlBuZ7PzgSk7FXQj8QgBWDkVmIkaMug86pTVh5oR1NDxLpihzW7q6qiYYuhmhkS64ZxSRE/K/kLvkJZMI/sIb2lBF/BxkZp3sw60B6UGTjpKUZqEB88RsOKy2N19QqIxCu9odMAMFN4bVQ4sBAw03UVbBi44WIm59pCQNqt3ecDInV6esjGbEEISGqcFbKBW5sPbrGEgGY+I5u8BSAgqzY3ZBO4kHEbvPQvVDR6ieQHyRAqSNmYKl9YPVBDAMUGKTtelsTa7RjYX7v4qGBnBeJ0uTOEQibyWsUels/NhF3r6Mc6lpmeawP9WFOMQibjKqCf5+6Eyq2mqGgZHZrdjmzC1ib6FdWYdraoKmJXJFtmWJwN3dqGv0jOAKNeXyBPkrS7VNPshQ1+EWz2Is9/rIvVgs1eUjkZq/AjACIvoS9oz3+ZymuV/2Q53UzZVbCg58JfpucqHYYV4bCdEftkQFipKbSzQeVY5X6QZHYhG7UFtFgZWbboqmLJouWQjd/aRsCenAB2FR1fRKmy7KVldpi7f9DyhUbMdpjmQCpAWVerw6hYx31vAaReM//JcnmZ1msVAFkZaKbvKl0WMvOYybpKNjRkBMzUXBsISNsMlWOVwiiWC8tGbm0iYLEvoBkZm43eQmKDjC0w82DZGC5M/kBqSR56vdZgfgVkMaB9BS07ozLL0/Ro35cyhW53fkAmNvl+FrEC6L3Ey7D6I4RM8bW6DCzPn6m81iGQFghk6q7VcIj2DppJujYAkHUYsoFbEACOJLeazd4CAJC2MjW1sbQi9pDN48IAkBWqDBWCA8euOBn0zKyYxOKaBlR7wFW+hQEjY2NPfQEERF/zSrDudSb6WoU/1t3JhF4b8Me6KpnAax3+WPFqpuoq3M5kAqsMKJu6hbwALmNlu9uh0hwU2wLY2VKlOGBNaQvZVK7tkb+xWD9tZ01F4xfpwk06yrGp4WSTTSRHFxtQeCAvgKRODrHBWFihg1tSIWoEBF9ylVjwFzPJV+kBwRcdnZ0NAAnruIlPzARe6wBIWwag+UtLBcCYDd9CsorlubC7Hxo2NhYn/5rZks3jwgCQpKWO2XQuCABpt8fpBQdtOjwkNiW6Ckp24D5xRAcqD8Zi8mcVzEVE7yVHhrY9yJiDwMW+TPC1eiRYLj8TeRVQJ7l8lgXAcFnqoMGYCboKFvRkd5oN3kKEDzTcy2ZwbeJey3yejtksLkhut3yptlsaFQvbNmXaxMyT+gqVgQyRo+1YTe+XJPVmZX6+f/v17nC+nh5un/X5/vX09Hy+/Pi8P07PL/JV958+n+5vv//lfP/hl9frzcbrh+OHzn/4V0LKl8Pb218kTNog). I really like your preference for straight lines on pipes – makes it look a lot cleaner. But I would say that my power poles look more organized :).

**Comment by Teoxoy** [comment]
I've done the straight pipe thing because that's how I usually do it in game. Regarding the power poles, I would have to agree on that one. :)
