### ISSUE TITLE
Cannot read property 'topLeft' of undefined

### ISSUE THREAD

**Issue by EKataskin** [Teoxoy/factorio-blueprint-editor#3]
Blueprint: https://pastebin.com/kjMB4YDC
After a little editing (deleted a few items at the top) - trying to copy results in an error: "Cannot read property 'topLeft' of undefined".
![error-screen](https://user-images.githubusercontent.com/1502765/42126655-b8555656-7c93-11e8-99ea-60442bad02dc.png)
![error-code](https://user-images.githubusercontent.com/1502765/42126656-bb607330-7c93-11e8-881b-2c76ef6eb081.png)

**Comment by EKataskin** [comment]
This has nothing to do with the rails.
I found a very simple way to reproduce this error.
![remove-entity-1](https://user-images.githubusercontent.com/1502765/42275289-7c49c248-7f98-11e8-8bd2-cd85906f4284.gif)

**Comment by Teoxoy** [comment]
I see what the problem is. You are deleting the first entity in the immutable entity array. At export it needs all blueprint corners to calculate the final entity positions and the default value for map.reduce is the first entity which got deleted. I will fix it in a bit.

**Comment by Teoxoy** [comment]
BTW, Thanks for reporting this!
