### ISSUE TITLE
Add less noisy background

### ISSUE THREAD

**Issue by Chronial** [Teoxoy/factorio-blueprint-editor#32]
Hey, first of thanks for this great tool :).

I am currently trying to improve demipixel's [oil outpost generator](http://autotorio.com/oil)  and would love to use your blueprint editor to view my generated blueprints. But I find the current background options to both be quite noisy, which makes it hard to see what's going on in these spread-out blueprints. Here's [an example](https://teoxoy.github.io/factorio-blueprint-editor/?source=0eJy9ndtu2zgURX8l0LNViKSu+YnO+6AonERI1dqy4UsxReB/HzupqCgnkvcxuPU0mGbirjkiF69bfokeVsd6u2vaQ3T/EjWPm3Yf3f/7Eu2b53a5uvzZ4c+2ju6j5lCvo0XULteXf9se19ufy8df0WkRNe1T/V90b06LW37Nnr4toro9NIemfvurP/63i2i72Z9/vGkvn3v+lTj7ki2iP+ffzb9k5096anb149vPk4X/i9vt8XD+3fP/Ufv20/Onv5xe/+Cw26y+P9Q/lr+bze7tT18J/nxvj+uHevf3f+Y6iLF/SWKJYgOhWBCl7IpSsIriMBKb+KKkLJQUQqlGS5IH4sjUJTGsdpJjKO4vibOsZ1OAIL7vXJoupyYl2Hd8UWgNtoJIjC+J0EmoFmsSiMRXJKOBgI51vu8YWt8xmGRN2lWFN/CAkr00kLGqBHtCmGU7Eie6cbCigJr1/fh1YCaxYJ71MwNX0R4PKFrrqyKGwWD9BxNtNx6nvKeDeTauRksS6ulYzLOmoNfEoqLtUGKa3Sw6me16T0IjQT3bFYVmWYtZ9nWF8WYU2koD1Wy3/hKzpWA1ASezJhmrSbB2gkp2DCRYScC5rO3URptBWtCxvhPTSBzm2Nh1XYc3LXCgZK0dRQnVjZ12x0DOIINVBbRswSfRzWWNUFuwp4NKtlObESuwYDVBLdtNIOVCPRgKqFm/o0ObGDjQs76liPl9MBJwzyAZJQnl2RScy3btRG5yBSNBN2a7lboVvSdUR04Hmm3OnzjRiWPeFmTqrnNUM2CkGgwhkmAYGfBUeg7a1CTNVRy8x1KoOHjPpVT1Fh5HBXCUnkNM0oIdHCQqDlo7zYyGw4hhNxgHYtOegzbAZIBN33Hw2geg03cctGVnhvi056DtCGSIT3sO2qlFhvi056BNyTLEp70/eP1W51Nav80Rn1p+O80Rn1p+O80Bn1p/3EgbbnNAp/3hOA8DsGmPQeu0uWpyysNQzU15Y36OuNS3UdoUKEdUamZQB6DShG+OAjBpwq9GAYjUzjARK5CJad86aBiASN/dlKC5owBM6rfbeUIvAJP2GLxqACbtGykPAxCpnWERVwAmtTMs4grApN34RoMoAY92ELQnUgIW9SM9jwJwaEVXaIks7RM+BrKy77avafuCJTIV7ShoGi+RmaijUyDzUEun0ExDeRTIej5hU1QKd/IgAHeWdAhAnSVbFhVgzg6CtkyrAG92ELTFUQVos2TPLCrAmp26aeuzCpBmSn8ciDMLOgXizILdP0yCbIHmfAxkBzTjYyDr9pSPAaizeya8m+IJ4M6cPZSZBJBnwafQ7H7StpVMojmYpx3vmQQxaMUeTEyiOUbiYRhEoQUfQ7Fq5x39GoOcIfnbZ7wYktEcIvF2t4zRnCLxZG4AjVr6Es0YZO8z4fcVwKN+Rk6sBuBRj0FbqBkDeNRj8GY9FvCox+AlTK1iBc87yTJWsYYn6twiR0iGvZdgLHKCRN/nMhawqN/0ky8yCMeBTEfNDByaw3hLbKWabVCi0K1mI5TI4RRboUwMQKUZf3xzgEoz/vjmFKt6Jgag0mIGDOQwPuPPzx2gUs/Bm587wKR+gCNiaPZGZUwmHIdmd5Q4wKWatT1xgEs1N0SZHIBK0xkeC6DSlD+wIPEln/HmKQyJL80wKUXSS24GjOsm7Twq38gTjuK6SD0FT6NAcMlT8J4IEFvyFDx1AaElT8HbwQciS56CtzkKBJYM31tAXKng91QgrFTweyoQVSpm6KnX3VnM0FOvu9NPuXiLVyCk1L9Jhtc8gYxSNQPFdXmWM1Bcl6d/oSlPW0A8yVPwFA6kk4oZKHB58mLRBsgmzbBGA5JJ/goL0eFAMqnHIFZDoc+U11mBYJK/IkB8KEAwycwwvgO5JH/Zi4kBTD8NXxtALGmOwwsgljTDQZ9IJcWHTfy82xzbp6nDlE/euhHs/aAioTSNVI4jhavSR7miSLT3cRmRW0KRRFtKQyGJFNM0Up/iERvb4d41+1HAk0h2AilYWxIBJ/DB8V6oZkTaCUUSc/5wbemjpKeR/OtoiTdERAxqGsmNI4Vr3jp7zxDFNiIgNY00ThSuSDp590i0F8UakZwCkcSZRrD+JlJUIBFvgBORKnRmwquRytx+M4BXIZW2R29Eh6uPytn0qI0RAaxJnmyMJ5iIRBYLG9No39FjRC4LAxJzo3AtSKVqf2OYKCGVqD0QzdNWBLemgUbvRgZ7D7yIcE0COfpdcyvCXNNAdqxRh6uQStMuHQMKVyGVp32jpr2E3Iqw1zRQOgYUrkI6U4+2oWDfLCASYBgQb4FmRRhskqjiV0hlan8LljZbtCIfNgnkry3RVvlWJMUgIN5+kRWZseluP3r9MFyFVKb2QLT5kBUpMmgxzbu7YUWebAooGeUJNnKIYNkUj7+Tx/viFZEwm+LJR3nC1Udj6XKG+mgs3X+FHq9AIn02CeQrxHOQyKFBQPIoNZiDRCJtEsj3edqq1YpsGgbEs7RIqU0B+eNe3sxDxNUQHjmKhXtgGkl7Ht4aWsTXIB7a171aEWNDJM07mbYizgZ1MAkUTNIi14YUSB7hBWtAIuAG8fAakEi6YVvlvK8jsiL0hhHJWx/hnpluKu1maNW688Sc3/FFKA7bZSCuyEQ+DiMiDq4iKodecuBtn4nU3PSytRhHCtaSRIAOvHfB24UVUbrpXdhslChcjd5be10/Ncd1XK/OH7RrHuPtZjWVVyYu8QchOxCr/4Zxop0GsTstGC9VYwc5PIyr4rt8EMsDq+Vm+NITOwjqYWAz3Fuxg+QehpWOrnXDUVU3PMWOi/dKfTvI9oFc/cBD5DJqLr/LxLuObjO96vuNC2K1blG944+M2S2m77h4isj0ou+/woCIdYPp/byU2Lj0nvfvQeEJNdNrPnb+O42JhtCL3p9h8qqV36D5/kVHRC695nsuXrTEDpKKh92yaeP9YbP9jKZ8k+hlocRBee/2/Xq5WsWr5fpTFL/6Ik5kBrlFFIcnp/wWlSdzgL2X+f7ShJ5/HOLzP1YTjeiyJ0FZNA+yjVdpcjZNqaFJ2TSVhsaSaQaBx6s0CZvGKGjYjXiQfrwGw27DgwzkNRh2Ex4kIa/B0FtwhsPQ26/CwvS6KBxMbzAKA9N7ksK/bMWUCvvS5Vsq5Esfl0qFfOlDdqmQL302UyrkS5/olQr5WnoD1tiX3oAV+rX0Bqzwr6U3YIWALbsBVwoDO3YDHkQXLwzxvnlul5/VpV/s8o4+K4WDHbs/VQoHO3Z/qoYO3uyWz3V8WLa/pvaPYnn4Guy+Q5XdBMQ7RhxkFnfLp+Vu8kyASXLDfrK/EBITz3+rEn9mbo42VN3CQ3twbhhZPH666ddrMOdUxSU3bBn7F13w3gDphnHFz6tj+dW55SRwjuqobu31z4t22uZ0WcV8nCjUIOaQL6nL5qgM8C77bA7fAC+z7zloh0EuqU7fFlFzqNfnz3pYHevtrmkvn/e73u277rtaPtSr88+/Nqu7r8fDmfNwF9+l9u6fswp+Lh9/7aPT6X+he6nv)

If you compare the same blueprint in [trakos' fpbviewer](http://fbpviewer.trakos.pl/b/c7wID0bAAwusRuvhy2YxTrfLdN0), it looks a lot cleaner due to the less noisy background, even though the pipes are not as nice.

It would be great if you could add something similar, so we can have the best of both worlds :).

**Comment by Teoxoy** [comment]
At the moment you can switch between dark and light mode (both checker pattern). I could make both colors customizable in the settings panel and also add an option for border color and width.

**Comment by Chronial** [comment]
Thx, I'm aware that you can switch between these two. I don't think a lot of customization is required. Just a third option that is either an extremely faint checker pattern or no checker pattern at all with gridlines – as in fpbviewer.

**Comment by Teoxoy** [comment]
What if I add a theme selector with: light, dark (both checker pattern) and one more grid which is going to look somewhat like the one you linked.

**Comment by Chronial** [comment]
That would be amazing :)

**Comment by Teoxoy** [comment]
Also, I've started to work about a month ago on a pipe generator for oil outposts myself because I wanted one that does what it was proposed [here](https://github.com/demipixel/factorio-generators/issues/25). I will see if I can finish it up or maybe push the branch that I've been working on to github this week. If you want I could tag you here -> #26 when I do so.

**Comment by Chronial** [comment]
That's exactly what I'm working on, too :). I'd be very interested in your results, so yes – please tag me. I will soon create a PR for trakos to see if he wants to merge my improvements into his outpost generator.

**Comment by Teoxoy** [comment]
I added a pattern selector in the end because it made more sense and you now also have 2 * 2 themes instead of 3 :)
