### ISSUE TITLE
Paste doesn't work in Firefox

### ISSUE THREAD

**Issue by mythmon** [Teoxoy/factorio-blueprint-editor#33]
`navigator.clipboard.readText()` doesn't work on the web in Firefox, [according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#Clipboard_availability).

This results in an error on the console when trying to paste a blueprint string:

> TypeError: navigator.clipboard.readText is not a function (app.ts:360:8)

As a workaround, you could use the older [execCommand based API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard#Using_execCommand()_2). It would be good to feature detect that `navigator.clipboard.readText` is undefined, and fallback to the older API.

Another workaround could be to pop up a text box that a user could put text into and then click a button. Not great, but again better than not working.

**Comment by mythmon** [comment]
The API problem I included originally seems to be fixed now, but pasting isn't quite working still. Now it prints what seems to be a JSON schema validation issue? This is from the Firefox devtools, so apologies for the weird copy/paste.

```
0: {…}
dataPath: ".blueprint.entities[268].name"
​​keyword: "entityName"
​​message: "should pass \"entityName\" keyword validation"
​​params: Object { keyword: "entityName" }
​​schemaPath: "#/properties/entities/items/properties/name/entityName"
​​<prototype>: Object { … }
​
1: {…}
​​dataPath: ""
​​keyword: "additionalProperties"
​​message: "should NOT have additional properties"
​​params: Object { additionalProperty: "blueprint" }
​​schemaPath: "#/oneOf/1/additionalProperties"
​​<prototype>: Object { … }
​
2: {…}
​​dataPath: ""
​​keyword: "oneOf"
​​message: "should match exactly one schema in oneOf"
​​params: Object { passingSchemas: null }
​​schemaPath: "#/oneOf"
​​<prototype>: Object { … }
​
length: 3
```

**Comment by Teoxoy** [comment]
Are you using modded items in the bp?
Can you also send me the bp string so I can take a look at it myself?

**Comment by mythmon** [comment]
I did have modded items in the blueprint. I can do some more testing with that this weekend. I'll file another issue if I run into trouble. Thanks for the help!

It might be nice to expose these sort of issues more prominently in the UI. As it stands, only savy users that look in the console would be able to find anything.

**Comment by Teoxoy** [comment]
We are working on the new UI and exponsing errors to the user is definetly on the todo list. Probably going to be bundled with #28.

**Comment by baryluk** [comment]
I think, a HTML textarea box to import explicitly the string would be a good idea. When I opened FBE first time I really had hard time figuring out how to import the blueprint! I needed to dig into options, read a lot of keybindings to figure it out, and I still not really like it, because, 1) it might not work on mobile, 2) It is easy to accidental overwrite your blueprint, 3) it adds to the confusion of the internal copy paste operations if they ever are to be implemented.

**Comment by Teoxoy** [comment]
@baryluk sorry, I somehow missed this comment.

You brought up some good points regarding UX.
Could you open an issue to track those?

FBE doesn't update the clipboard in real time. There is no way to do that with a browser in the first place.
