### ISSUE TITLE
Inventory Dialog Style

### ISSUE THREAD

**Issue by SIPS1980** [Teoxoy/factorio-blueprint-editor#34]
Hello Teoxoy,

First: great job on your project so far - well done.

While I was checking it out I figured I could try to see if I can make the Inventory match the game itself (eat least closely) - here is the result:

![image](https://user-images.githubusercontent.com/25469040/50669638-5a88c500-0f94-11e9-8e5b-6744a73c7507.png)

If you like it feel free to change / alter and / or integrate it into your tool - In the attached ZIP are my changes which were only done to 'inventory.ts' file
[inventory.zip](https://github.com/Teoxoy/factorio-blueprint-editor/files/2725772/inventory.zip)

Cheers - keep up the awesome work

**Comment by Teoxoy** [comment]
This looks great!
I changed some things and also applied the background style to the info and editEntity containers.
Thanks a lot for your contribution.

**Comment by SIPS1980** [comment]
Thank you Teoxoy - I appreciate the feedback. Please see my newest advantage in #35
