### ISSUE TITLE
Adding Toolbelt

### ISSUE THREAD

**Issue by SIPS1980** [Teoxoy/factorio-blueprint-editor#35]
Hello Teoxoy,

While I'm not sure if the tool belt was meant to be developed and integrated with #28 though I thought I give it a shot - here is the result (I know the belt loop on top doesn't make a lot of sense...):
![image](https://user-images.githubusercontent.com/25469040/50708057-f8ca6880-1030-11e9-89e8-f62293c7fcdf.png)

The tool belt also supports already 2 rows which if a some point a setting is implemented to have 2 rows only the method ".setRows()" needs to be called accordingly. Also, the key bindings for number 1 to 5 (including shift) are available.

This time around I had to change 2 files and created 1 more in order to make it work - find therefore in the attached ZIP file the following:
* New Container File: "toolbelt.ts"
* Changed Files: "app.ts" and "globals.ts"

One issue is still open which would most likely be a more major change to solve it is when rolling over with the mouse above the tool belt the icon in the mouse hand is not shown anymore. I have already some ideas on how to fix this though nothing practical at this point.
[Toolbelt.zip](https://github.com/Teoxoy/factorio-blueprint-editor/files/2728374/Toolbelt.zip)

Cheers

**Comment by Teoxoy** [comment]
Hey! Thanks again for your work! 👍
I will take a look in a bit but don't you want to submit a PR for this and any future contributions?
It's fine if you don't, I can commit the changes myself but just asking.

**Comment by SIPS1980** [comment]
Sounds good - have added a pull request #36 (never did that before ... so took a bit)
