### ISSUE TITLE
Power Switch breaks the render

### ISSUE THREAD

**Issue by GitHed** [Teoxoy/factorio-blueprint-editor#4]
I had an issue with a blueprint book not rendering, after narrowing it down to which blueprint was causing the issue, I went through and found a two item combo that breaks rendering.

A powerswitch, with a substation, connected via a copper wire. 

Example:
https://teoxoy.github.io/factorio-blueprint-editor/?source=https://pastebin.com/LbdUgad8

Image of the blueprint in the pastebin link above is attached.
The concrete is not in the blueprint.

![editorbug](https://user-images.githubusercontent.com/3461533/44300140-cead1f80-a2b6-11e8-808b-78eb23eae5b5.JPG)

Error:
Array(3) [ {…}, {…}, {…} ] main.js:43:4643

[
  {
    "keyword": "additionalProperties",
    "dataPath": ".blueprint.entities[0].connections",
    "schemaPath": "#/properties/entities/items/properties/connections/additionalProperties",
    "params": {
      "additionalProperty": "Cu1"
    },
    "message": "should NOT have additional properties"
  },
  {
    "keyword": "additionalProperties",
    "dataPath": "",
    "schemaPath": "#/oneOf/1/additionalProperties",
    "params": {
      "additionalProperty": "blueprint"
    },
    "message": "should NOT have additional properties"
  },
  {
    "keyword": "oneOf",
    "dataPath": "",
    "schemaPath": "#/oneOf",
    "params": {
      "passingSchemas": null
    },
    "message": "should match exactly one schema in oneOf"
  }
]

**Comment by Teoxoy** [comment]
Sorry for the late response. I didn't get an email notification for your issue for some reason.

I see what's causing the issue. I never tested that configuration before, it should be an easy fix tho.

Thanks for the report.
