### ISSUE TITLE
Crash when pasting inappropriate entity settings

### ISSUE THREAD

**Issue by xiagu** [Teoxoy/factorio-blueprint-editor#52]
#### Steps to reproduce
1. Create an assembler and set a recipe.
2. Place a splitter.
3. Attempt to copy the recipe from the assembler to the splitter.

([Here's a blueprint with these two objects already populated.](https://teoxoy.github.io/factorio-blueprint-editor/?source=0eJyNkN1qwzAMhd/lXDslDqztfLnXGGU4qegEthJsdSwEv/ucdIyywbZLW+fnkxb04UpTYlG4BTyMkuGeF2S+iA/rn84TwYGVIgzEx/Xlc6bYB5ZLE/3wykKNRTFgOdM7nC3mz4g8BValdGfrysmARFmZbhi/1RlMY67SUdaOam86gxmurYFnTjTcRu1n5Pwi19jXPmcN6pQ3Jk1e8jQmbXoKipX7O9+PHrt7+F/Rts+2tbu7s8EbpbxZ9sdD1x3tY3uo6MFXhKp8+lKW8gEHl4qA
))

#### Expected
Nothing happens.

#### Actual
Editor partially crashes, and deleting entities becomes impossible until after a refresh.

**Comment by Teoxoy** [comment]
Thanks for the report!
