### ISSUE TITLE
Add version of factorio (actually 0.16)

### ISSUE THREAD

**Issue by jnf27170** [Teoxoy/factorio-blueprint-editor#53]
Just to show on main page if the blueprint editor is compatible with the factorio version (in prevision of the incoming 0.17).

**Comment by Teoxoy** [comment]
You mean specifying the supported factorio version on the readme?

**Comment by jnf27170** [comment]
I was thinking on the main page (toolbar container) but README is fine too.

**Comment by Teoxoy** [comment]
Oh, I might add it in the info container then.
