### ISSUE TITLE
Add information panel with some details (e.g. input/output per seconde of the recipe)

### ISSUE THREAD

**Issue by jnf27170** [Teoxoy/factorio-blueprint-editor#54]
I'm already working on it and will suggest a commit soon.

**Comment by jnf27170** [comment]
Commit is ready but I don't have rights to push the commit.

**Comment by Teoxoy** [comment]
You have to commit to your fork then open a PR.

**Comment by jnf27170** [comment]
Here you will find my fork with the new info panel:
[link to my fork with sample](https://jnf27170.github.io/factorio-blueprint-editor/?source=0eJyd192uojAQAOB3mWua9Af/uNzXODnZFJ3VZqGQtu7RGN79FDUbVlaYcmW09JthmGJ7g7I6Y+uMDVDcwOwb66H4uIE3R6ur/rdwbREKMAFryMDquv8WnLa+bVxgJVYBugyMPeAFCtFls5N/aR/YW0F2nxmgDSYYfOTynKa9x7qsjD2yWu9PxiITEW0bHy9tbB8uTmcqg2v8iInAwTjcP8b407z+tOe6RBczzSCOmkd+rrHsiNqxrxNiBf1NvI8qx1E5MahcHFSNg1LvVNGCvjyRcWXze7yXcHIULk8xFc1cpZiSZq5TTEEzNwkmp5HbBJKY5S6BJBZT8AST+NCFGJj/e2m8a1E5K8tkWRFllSxLopwny4Ior1JlToTXqTA1400qTC3yNhWm9sVwzeGldeg9tZ3VHC75ElwRcbEEl0RcLsEFEVcLcE608wU2Ne/VApta8PUCm9opw1VZnp1Fx4z16EIcfdfcTM3umYZrcsJTVG+4FKsm7rFOOm49D1O5PqrL8tmtFn99f0yggpiw+ud/0FRhsq6cqg6Xng96/3sCJaeqRuhswpJq5/3J4H6UKAbHlgz+oPP3OevtRsqt2PFNNCsdmzle+ePvlV33DUAlVQ8=)

I can't open a PR to your repo because your repo is protected.

**Comment by Teoxoy** [comment]
Nice work!
The repo should not be protected. I don't even think there is such a thing.
You can find the open a PR button here:
![image](https://user-images.githubusercontent.com/28601907/53293391-5bd7b080-37d3-11e9-9ea4-7efcf14d4510.png)

But there is a problem, you modified the README and some other files I think.
So you would need to remove some commits from the PR.
Just searched it up and found [this](https://stackoverflow.com/a/51400593).

**Comment by Teoxoy** [comment]
Actually, I would advise you to keep your forks master in sync with the upstream master  (this repo).

Then, when you want to propose a change to master and your fork, make a new branch and work on that. When you are done with the said changes you can submit a PR.

If you want to maintain a separate version of the repo, you can do that too, just on another branch. And set it as the default branch on github.

Just some tips 😃

**Comment by jnf27170** [comment]
That's true I can open a PR on my fork to your repo. Thanks for the tip !
For your information, this is the first time i'm using git and git-hub and it is quite difficult to understand all the process. Originally, I was thinking to work only on your repo, and the fact to work on mine was quite difficult to change with the learning of all GIT commands... Moreover, I needed to modify your package-lock.json because it is quite outdated (especially the pathfinding package that was giving me errors) and your package.json because the GIT INIT command wants to add bugs url and homepage url).

So what I can do:
**Solution 1°)**
I can commit my actual master to your actuel master and I will modify back some small changes on README and package.json. I can do a PR but only on existing branch, if you want me to push on a new branch, you need to create it or to add me as collaborator or to modify the branch protection rules in your settings. Below is the default installation of my new github fork :
![image](https://user-images.githubusercontent.com/47829136/53299778-819a9f00-383f-11e9-8346-eadb1a45b3f7.png)
**Solution 2°)**
I delete everything, clone again your repo, and bring the only modifications relatives to the new InfoProd panel. This is ok for me as I haven't done so much but you will lose some good modifications on package.json and package-lock.json. About this I recommend you to update all the local packages from NPM/node.

About package.json, what is doing "git reset -- stats" ?

I don't want to maintain my fork and your repo. I prefer to help you only on your repo. My fork would eventually be usefull because it will be a kind of 2nd gh-pages for testing purpose.

Tell me what you prefer

**Comment by Teoxoy** [comment]
I agree that git has a learning curve when you also have to deal with githubs way of doing things (forks and PRs).

I would go with solution 2. Create a new branch on your fork, add the changes, then start a PR. Regarding package.json and package-lock.json, I will push a commit so sort those out.

[git reset -- (FOLDER or FILE)](https://git-scm.com/docs/git-reset#git-reset-Resetasinglefileintheindex) - removes a file or folder from the commit (I was generating stats about the project when I was building with webpack and I didn't want to push the stats folder in production) - I'm not generating any stats now so I should probably remove that command from the build process

BTW, If you would like to commit more frequently, you could come on discord to discuss and I might give you write access as I did with SIPS1980 (he had a few great additions to the project and wanted to commit more frequently, so I gave him write access) - this way you won't have to maintain your fork.

**Comment by Teoxoy** [comment]
I rebuilt package-lock (3eaa6f4), tell me if you have any issues.
