### ISSUE TITLE
2nd sample blueprint link of README.md is not working

### ISSUE THREAD

**Issue by jnf27170** [Teoxoy/factorio-blueprint-editor#55]
This blueprint passed through the url is not working anymore :
[https://teoxoy.github.io/factorio-blueprint-editor/?source=https://pastebin.com/Xp9u7NaA&index=1&renderOnly](https://teoxoy.github.io/factorio-blueprint-editor/?source=https://pastebin.com/Xp9u7NaA&index=1&renderOnly)

We need to modify the README.

**Comment by Teoxoy** [comment]
Works fine for me. Can you check the console for any errors?

**Comment by jnf27170** [comment]
The link is working at home (recent chrome) but it was not working at work (old chrome).
I will check again probably tomorow if I have time.

**Comment by Teoxoy** [comment]
Ok!
