### ISSUE TITLE
Try PNG8 instead of PNG32 to decrease loading time

### ISSUE THREAD

**Issue by jnf27170** [Teoxoy/factorio-blueprint-editor#56]
I found a website [http://www.imagesmaller.com/](http://www.imagesmaller.com/) that is converting to png8 and keeping the transparency.

**Comment by Teoxoy** [comment]
I tried to do some sort of compression before but the reduction in size was minimal.

I thought PNG8 would make the sprites look awful but it seems I was wrong. I just tested it and I could only see some compression artifacts when I was pretty much all the way zoomed in.

The HR entities went from 15.7MB to 4.76MB (~70% reduction in size).

So, what I will probably do is:
- add PNG8 spritesheets to the factorio-data repo
- replace the HR Entities checkbox with a selection:
  - `Low Resolution (PNG8, <size>)`
  - `High Resolution (PNG8, <size>)` <---- selected by default
  - `Low Resolution (PNG32, <size>)`
  - `High Resolution (PNG32, <size>)`

**Comment by jnf27170** [comment]
Yes I'm quite sure this is going to work because the only loss is the quantity of colors and when I tried few hours ago, the quality loss was about 5% (from my point of view) and the size was what your are saying (15MB ->5MB).
If this works, this is going to decrease loading time (and also maybe the RAM used into the browser and/or the reactivity/FPS of PIXI scene).
Another way to improve the loading time is to start with LR-PNG8 and then continue loading HR-PNG8 in the background.

**Comment by Teoxoy** [comment]
> Another way to improve the loading time is to start with LR-PNG8 and then continue loading HR-PNG8 in the background.

Yeah, this is also a good idea.
