### ISSUE TITLE
Steel furnace placement off-by-one

### ISSUE THREAD

**Issue by HiroP0** [Teoxoy/factorio-blueprint-editor#6]
0.16.51 36654 win64

Blueprints with steel furnaces, which went through the editor, might have their placement positions off by one. I observed  y+1 (upwards) and x-1, y-1 (down,left). Editor shows it fine, placement preview also looks fine, but actual placement is off.
 
![editor](https://user-images.githubusercontent.com/1537523/46247185-eb855880-c407-11e8-9b87-8be7af922193.PNG)
![placed](https://user-images.githubusercontent.com/1537523/46247186-ede7b280-c407-11e8-9896-672caa742bec.PNG)
![placementpreview](https://user-images.githubusercontent.com/1537523/46247188-f213d000-c407-11e8-944c-370c32164221.PNG)

**Comment by Teoxoy** [comment]
Can you send me the bp string?

**Comment by Teoxoy** [comment]
I think I fixed it. Can you confirm?

**Comment by HiroP0** [comment]
Looks good. Awesome editor.
Thx

**Comment by Teoxoy** [comment]
Thanks for reporting the bug!
