### ISSUE TITLE
[BUG] Really Low FPS After 0.17

### ISSUE THREAD

**Issue by deitrix** [Teoxoy/factorio-blueprint-editor#61]
**Describe the bug**
The FPS is really low after 0.17 was released. I used to easily get 60FPS and now for some reason it's consistently below 15FPS.

**To Reproduce**
Sorry, not entirely sure. If you have any tips for debugging this on my end, do let me know.

**Expected behavior**
MOAR FPS

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 1809 (64-bit)
 - Browser: Chrome 72.0.3626.121 (64-bit)

**Additional context**
Running on a regular 1080p monitor.

I have a feeling it may be related to #56, but that's just a guess.

**Comment by Teoxoy** [comment]
Can you send a specific blueprint string where you are getting 15FPS and were getting 60FPS before?

**Comment by deitrix** [comment]
No need. This is after just loading the page. No entities on the screen

**Comment by Teoxoy** [comment]
Ohh. Does this always happen or just sometimes? Can you try on firefox if you have it?

**Comment by Teoxoy** [comment]
Is this still happening?

**Comment by Teoxoy** [comment]
I think you were using WebGL1 and it was using too much VRAM. I halved WebGL1 VRAM usage in c06d977.

I will close this issue for now. Feel free to reopen it if you still have this issue.

**Comment by deitrix** [comment]
Eventually got around to fixing this on my end. The BP editor was working fine in Firefox. The issue ended up being that I didn't have hardware acceleration enabled in Chrome. I also enabled all of the WebGL under chrome://flags for good measure and voila! Working again :)

**Comment by Teoxoy** [comment]
Awesome!
