### ISSUE TITLE
Not loading on work computers

### ISSUE THREAD

**Issue by TheBear17** [Teoxoy/factorio-blueprint-editor#63]
On a previous version of your blueprint editor I used it successfully on my work computers (I work some nights and have a lot of downtime).  Recently I tried again but am unable to load on at least three of my work computers.  I have included a screenshot of the error coming up on the Console.  This occurs in both IE and chrome.
The website works successfully on my home computer.  I am unsure if it is an actual bug or if your newer version is not able to be used on my work computers.
I am unsure if this is a bug or if my work computers are simply incompatible with your updated version of Factorio Blueprint Editor, but I thought I should post this and see if it is possible to run at work.

![Factorio Blueprint Editor F12](https://user-images.githubusercontent.com/49335298/55680773-5c3b8f00-58db-11e9-9419-3d688a9f6288.PNG)

**Comment by Teoxoy** [comment]
Check out this website and send me a screenshot: http://webglreport.com/?v=1
Maybe your work computers are not WebGL compatibe

**Comment by TheBear17** [comment]
Absolutely that was it.  WebGL1 worked on IE but not WebGL2.  Neither worked for chrome.
Tried all the steps recommended to turn WebGL on but did not seem to get any success with this.  Might be locked down by the administrator.
Downloaded Iron SRWare and works great.  My apologies for bothering you.
Thank you for your help!

**Comment by Teoxoy** [comment]
No problem. Glad you managed to solve it :)
