### ISSUE TITLE
Configurable grid size

### ISSUE THREAD

**Issue by cajopa** [Teoxoy/factorio-blueprint-editor#64]
I would like to request a feature to make the size of the canvas configurable. This would be very useful for megabase design, as many such designs are chunk-oriented (32x32 or multiple thereof). I have found myself carefully laying down walls to indicate my boundaries, then having to delete them carefully by hand afterward.

**Comment by Teoxoy** [comment]
I've been thinking that I should add this too but to make the size of the grid configurable I need to use the middle of the grid as the origin for all entity positions. Currently the origin is the upper left corner. This is quite simple in theory but having entities with negative x and y will have unexpected side effects and will break some logic.

Anyway, I'm just saying that I would like to add this but it will take time to test all the functionality of the editor with this new change.

**Comment by Teoxoy** [comment]
@cajopa I've done some work on this and came to the conclusion that there is a much simpler solution.

What do you think about a chunk overlay that could be turned on and off from the settings?

Implementing a chunk overlay would be much easier than adding the logic necessary to make the editor shrink and expand based on a blueprint.

I will also make the editing area bigger - probably 1000x1000. The area itself doesn't have any performance impact, filling it with entities would ofc.

**Comment by cajopa** [comment]
That sounds like an elegant solution - I'm a big fan of writing less code. You might have to implement some logic for placing blueprints along those chunk boundaries, though. Perhaps always place the top left at the corner of a chunk?

**Comment by Teoxoy** [comment]
I think I will align the chunk grid so that the origin (0, 0) of the editor area is the mid point of a chunk. This way if you have a blueprint that is exactly 32x32 it will fit perfectly inside because the mid point of blueprints is also at (0, 0).

**Comment by Teoxoy** [comment]
@cajopa I've implemented this. Let me know what you think!
