### ISSUE TITLE
[BUG] left click seems to be not working.

### ISSUE THREAD

**Issue by cablegunmaster** [Teoxoy/factorio-blueprint-editor#65]
**Describe the bug**
Trying to open up the inventory, the inventory does not show to add more entities.

**To Reproduce**
Open up the web browser, and wonder if this should be fully functional, or does a local version need to be used?

I used Firefox, and chrome. (latest versions).

**Expected behavior**
Expected to show a input or menu to add new entities.

**Desktop (please complete the following information):**
OS: Windows
Browsers: Chrome, Firefox.
Internet explorer is showing only loading.

I hope, you got time to fix it !
Good luck :).

**Comment by cablegunmaster** [comment]
'dat.gui.closed' stays false.
Even when I change the standard: "Open Entity G U I " to the letter 'z'.

I might be doing something completely wrong , so let me know :) .

**Comment by Teoxoy** [comment]
By default it's bound to E. Are you saying that pressing E doesn't bring up the inventory?

**Comment by cablegunmaster** [comment]
Ah okay, for some weird reason I was expecting first click to open the inventory to build.
No idea why I was thinking this. (might be web intuitivity).

Suggestion: to put this message on screen in the beginning; 'To start building press E for inventory'
and when E is pressed remove the message and check by refresh and keep it as an boolean, and when blueprints are loaded (ignore the message?)

Also wondering what is "open Entity gui?" as I have misstaken this for the inventory.

**Comment by Teoxoy** [comment]
That's a valid suggestion.
Open entity GUI is left click by default and it opens the entity inventory so that you can change filters, recipes and so on.
I will close this issue and make a new feature issue for a "welcome message".
