### ISSUE TITLE
Copy and delete selections

### ISSUE THREAD

**Issue by Teoxoy** [Teoxoy/factorio-blueprint-editor#7]
Copy selection (ctrl + left click to start) - this would behave as the other paint containers
Delete selection (ctrl + right click to start)
Clear selections with Q

**Comment by FrederickDoering** [comment]
click + drag is currently used to move around the map, would this functionality be replaced?

I think from an intuitive point of view when I first select an area I would just expect to be able to shift the entities with the arrow buttons (I've wanted to do this so many times)

UI wise it might be nice to have this feature similar to how the game blueprints work.

**Comment by Teoxoy** [comment]
I have done some work locally a while back but this feature requires some other things to be in place first. The ability to transfer the connection information to an entity would be one of those.

Regarding the shortcut, it would be ctrl/cmd + left click for selecting the area and ctrl/cmd + right click for destructing the entities in the area.
