### ISSUE TITLE
[BUG] Heat interface settings cannot be modified

### ISSUE THREAD

**Issue by Bilka2** [Teoxoy/factorio-blueprint-editor#70]
**Describe the bug**
Heat interface settings cannot be modified.

**To Reproduce**
1. Go on https://teoxoy.github.io/factorio-blueprint-editor
2. Place heat interface.
2. Try to open it.

**Expected behavior**
Heat interface settings can be changed by opening it.

**Desktop**

-   OS: Windows 10
-   Browser: Firefox 67.0.4

**Comment by Teoxoy** [comment]
Track the progress on this issue here: #73
