### ISSUE TITLE
More entity settings

### ISSUE THREAD

**Issue by Teoxoy** [Teoxoy/factorio-blueprint-editor#8]
- [x] item filters
- [x] splitter settings
- [x] entity preview
- [x] requester chest
- [x] buffer chest
- [x] storage chest
- [x] beacon editor
- [x] electric mining drill

**Comment by SIPS1980** [comment]
Quick Update: the base for the Editor UI to show the entity image is finished for Splitters, Inserters, Electric Mining Drill and Bacons. While working with issues, current status is checked in in branch Editors

![image](https://user-images.githubusercontent.com/25469040/50801577-5a016e80-12b3-11e9-8733-3edb2ed3ff33.png)

![image](https://user-images.githubusercontent.com/25469040/50801592-684f8a80-12b3-11e9-9370-693889c959ff.png)

![image](https://user-images.githubusercontent.com/25469040/50801604-73a2b600-12b3-11e9-90fa-956cc281f44d.png)

**Comment by SIPS1980** [comment]
Interim update - Assembly Machine Editor finished - let me know what you think

![image](https://user-images.githubusercontent.com/25469040/51077979-2d1ad600-167c-11e9-90e8-048994dd0593.png)

**Comment by Teoxoy** [comment]
Awesome stuff!

**Comment by SIPS1980** [comment]
Quick update - Filters for Editor like Splitters and Inserters are finished (Open is setting stack size)
![image](https://user-images.githubusercontent.com/25469040/51089399-61ed6280-173a-11e9-8cff-9a40ce657c86.png)

**Comment by SIPS1980** [comment]
Facotrio Splitter Editor"
![image](https://user-images.githubusercontent.com/25469040/51285744-0a5f2900-19be-11e9-8f9c-442c49440a91.png)

Blueprint Editor Splitter Editor:
![image](https://user-images.githubusercontent.com/25469040/51285761-1ea32600-19be-11e9-808c-b25f7382c541.png)

**Comment by SIPS1980** [comment]
![image](https://user-images.githubusercontent.com/25469040/52157397-c8401380-265c-11e9-903d-9d0969f2a7fb.png)

**Comment by Teoxoy** [comment]
I guess we can close this.
