### ISSUE TITLE
[BUG] Wires are preserved when it's the input and output of an combinator

### ISSUE THREAD

**Issue by TheSnoozer** [Teoxoy/factorio-blueprint-editor#81]
**Describe the bug**
Hello, thank you for this awesome tool. I noticed a small bug when a combinator has a wire connected from it's output to it's input the wire might not be removed when the combinator is removed

**To Reproduce**

1. Go to https://teoxoy.github.io/factorio-blueprint-editor/?source=https://pastebin.com/frtpccDh
2. Remove all decider combinators or all entities altogether
3. See that the wire that's the combinator input and output is preserved even when the combinator is deleted

**Expected behavior**
Even though wires are 'free' with bots, those should go away when the combinator is deleted

**Screenshots**
![Screenshot from 2019-07-15 23-43-04](https://user-images.githubusercontent.com/6849390/61264391-6a127300-a75a-11e9-91a5-1596cb3ef6c0.png)

**Desktop (please complete the following information):**

-   OS: ``Ubuntu 18.04.2 LTS``
-   Browser: ``Firefox 68.0 (64-bit)`` & ``Chrome 75.0.3770.100 (Official Build) (64-bit)``

**Additional context**
Blueprint:
https://pastebin.com/frtpccDh
```
0eNrNll+P2jAMwL/KKc/tiZQDjmq3h32N6VSlrQFLbVIlLjqE+t3ntMA6WIHqbhMvFDu2Y/uXf3uRFjVUFjWJeC8wM9qJ+OdeOFxrVXgd7SoQsUCCUgRCq9JLOWSYgw0zU6aoFRkrmkCgzuFDxLIJbgaAj8qCcyFZpV1lLIUpFNQLEjXvgQBNSAhdSq2wS3RdpmB5lmvJBKIyjl2N9hlwuFA+zwKx4z8Rz5GjhawbnQeCiyZriiSFjdoie7PLIWbCY3kbx3ntCq2j5KK0LVqqWXPKqLMILeS+It9UUr7Ds6WXykrZNstYvLGPqamqR0RdWwDdxa12nGCtKVlZUyaoOY6IV6pw0HTz6q7MNnnpf3xKvWYiS1O2RJvVSK3IjWffaMA4+tNYsnHjcZ/BicbBiTo0k+dZ8w9x9Bp3BDL5Ah6wBbujDer1FShk6zFM5AWTQHTpX+cR9Vh4+WWQ7T3RhuhOR9Gd/Be4F3ttfs7224OwnY5CJs+GZ2fy/Op2nV4PJu/j/TLyqH0Q4G+PCVx+zSac3bpLL8AcTlk5QOU46YlKqxw8Kr/7BhVmjY4wG+V0nAi0SgtIcnT+e7i4fg9bUHmyUTr3wYmrd13ng36mrb4zLU3OQSaf4vK3Rs9PjT7WdcdxN9TkFRYEduCNdXOp176nsvfQev9ktXyttO+yuPcOZKqKFxDrfvAyeqKNNfV6wwv/qU0AfM28S1xb8mI6kYvla7RcvDbNL5n1lB4=
```

**Comment by Teoxoy** [comment]
Thanks for the report!
I've done some work on the wire connections yesterday and it seems I overlooked some things.
It also looks like the blueprint is off-grid. Need to fix that too.
